### ISSUE TITLE
Decrypt Feature requires CSRF token

### ISSUE THREAD

**Issue by dr01d3r** [jhu-redcap/IP-ENCRYPT#1]
When attempting to decrypt in the Control Center, the module crashes due to the absence of the `redcap_csrf_token`.  The following adjustments to the `$.ajax` call have been tested to work.

```js
data: `decrypttxt=${iptext}&redcap_csrf_token=<?=$module->getCSRFToken()?>`,
contentType: 'application/x-www-form-urlencoded',
```

**Comment by devilsphere** [comment]
Thank you very much, the change has been applied and a new version should be out soon.
